### ISSUE TITLE
Full View of Image on iOS 12 Beta 1 does not work

### ISSUE THREAD

**Issue by ericcirone** [mluisbrown/Memories#2]
When you enter in to the full view of the image on iOS 12 Beta 1 you are presented with nothing. I've tried to track it down in the simulator and it seems that in ZoomingPhotoView.swift in adjustImageConstraints it seems to be messing up. Not sure if its the Cartography framework or not.

disclaimer: i am a developer, just not an iOS dev.

**Comment by mluisbrown** [comment]
This was fixed in later betas if iOS 12. It was a bug in the iOS beta.
